name: Trigger BookCarts tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    steps:
      - name: Get repository 
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run the tests
        run: npm run cy:ran
      - name: Generate report
        run: npm run generate:report
        if: failure()||success()
      - name: Save report
        uses: actions/upload-artifact@v3
        with:
            path: mochawesome-report
            name: Test report
        if: failure()||success()
      - name: Get report
        uses: actions/upload-artifact@v3
        with:
            name: Test report
        if: failure()||success()

